<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>AI</RootNamespace>
    <AssemblyName>AI.Charts</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AI.Charts.WinForms" />
    <InternalsVisibleTo Include="AI.Charts.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.DSP\AI.DSP.csproj" />
    <ProjectReference Include="..\AI\AI.csproj" />
  </ItemGroup>

</Project>
