<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <IsPublishable>false</IsPublishable>
    <RootNamespace>AI</RootNamespace>
    <AssemblyName>AI.Fuzzy</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI\AI.csproj" />
    <ProjectReference Include="..\AI.KNN\AI.KNN.csproj" />
    <ProjectReference Include="..\AI.ML\AI.ML.csproj" />
  </ItemGroup>

</Project>
