<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AiFrameworkDemo</RootNamespace>
    <AssemblyName>AiFrameworkDemo</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\AI.LLM\AI.LLM.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI\AI.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.ClassicMath\AI.ClassicMath.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Charts\AI.Charts.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Charts.JS\AI.Charts.JS.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.ControlSystems\AI.ControlSystems.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.ComputerVision\AI.ComputerVision.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.DSP\AI.DSP.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.ML\AI.ML.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.NeuralNetworks\AI.NeuralNetworks.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Geometry\AI.Geometry.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Algorithms\AI.Algorithms.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Faiss\AI.Faiss.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.ONNX\AI.ONNX.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.DataPrepaire\AI.DataPrepaire.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.NLP\AI.NLP.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Solvers.Math\AI.Solvers.Math.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.SignalLabs\AI.SignalLabs.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Fuzzy\AI.Fuzzy.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Economics\AI.Economics.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.LLM\AI.LLM.csproj" />
    <ProjectReference Include="..\..\..\..\src\AI.Microwave\AI.Microwave.csproj" />
  </ItemGroup>

</Project>
