<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <IsPublishable>false</IsPublishable>
    <RootNamespace>AI.ML.NeuralNetworks.Onnx</RootNamespace>
    <AssemblyName>AI.NeuralNetworks.Onnx</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.NeuralNetworks\AI.NeuralNetworks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.29.3" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.16.0" />
    <PackageReference Include="Grpc.Tools" Version="2.68.1">
      <PrivateAssets>All</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Proto\onnx.proto" GrpcServices="None" ProtoRoot="Proto" />
  </ItemGroup>

</Project>
