<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <IsPublishable>false</IsPublishable>
    <RootNamespace>AI</RootNamespace>
    <AssemblyName>AI.ML</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
    <NoWarn>$(NoWarn);SYSLIB0011</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.ClassicMath\AI.ClassicMath.csproj" />
  </ItemGroup>


</Project>
