<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AI.Microwave</RootNamespace>
    <AssemblyName>AI.Microwave</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Solvers.Math\AI.Solvers.Math.csproj" />
  </ItemGroup>

</Project>
