<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>AI.Charts.Avalonia</RootNamespace>
    <AssemblyName>AI.Charts.Avalonia</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.1" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI.Charts\AI.Charts.csproj" />
  </ItemGroup>

</Project>
