<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>Latest</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AI\AI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="AI.Faiss.props">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="runtimes\win-x64\native\*.*">
      <Pack>true</Pack>
      <PackagePath>\runtimes\win-x64\native\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
